@startuml

title __Class Diagram__\n

set namespaceseparator none

namespace javafx.application {
  class Application {}
}

namespace jobfitpackage {
  class JobList {}
  class MainScreenController {}
  class Profile {}
  class ProfileList {}
  class SignInController {}
  class EditProfileController {}
  class SignUpController {}
  class SessionManager {}
  class Job {}
  class Main {}
}

SignUpController -up[hidden]- Main
Main -l[hidden]- Job
Main -r[hidden]- SessionManager

EditProfileController o-- Profile : profile
Main -up-|> Application

MainScreenController o-- JobList : jobList
MainScreenController o-- Profile : profile
SignInController o-- Profile : currentProfile
SignInController o-- ProfileList : profileList
SignUpController o-- ProfileList : profileList

@enduml
